<?php
declare(strict_types=1);

/* Builds a self-contained Chapter IV manuscript with low-fidelity figures. */
$outDir = __DIR__ . DIRECTORY_SEPARATOR . 'capstone_build';
if (!is_dir($outDir)) mkdir($outDir, 0777, true);

function esc(string $s): string { return htmlspecialchars($s, ENT_XML1 | ENT_QUOTES, 'UTF-8'); }
function canvas(string $name, int $w = 1400, int $h = 800) {
    global $outDir;
    $im = imagecreatetruecolor($w, $h);
    imagefill($im, 0, 0, imagecolorallocate($im, 255, 255, 255));
    return [$im, $outDir . DIRECTORY_SEPARATOR . $name, $w, $h];
}
function line($im, int $x1, int $y1, int $x2, int $y2, int $width = 3): void {
    $c = imagecolorallocate($im, 45, 45, 45); imagesetthickness($im, $width); imageline($im, $x1, $y1, $x2, $y2, $c);
}
function arrow($im, int $x1, int $y1, int $x2, int $y2): void {
    line($im, $x1, $y1, $x2, $y2); $a = atan2($y2 - $y1, $x2 - $x1);
    line($im, $x2, $y2, (int)($x2 - 16*cos($a-.45)), (int)($y2 - 16*sin($a-.45)));
    line($im, $x2, $y2, (int)($x2 - 16*cos($a+.45)), (int)($y2 - 16*sin($a+.45)));
}
function box($im, int $x, int $y, int $w, int $h, string $text, int $size = 22): void {
    $black = imagecolorallocate($im, 35, 35, 35); $fill = imagecolorallocate($im, 245, 245, 245);
    imagefilledrectangle($im, $x, $y, $x+$w, $y+$h, $fill); imagesetthickness($im, 3); imagerectangle($im, $x, $y, $x+$w, $y+$h, $black);
    $font = 'C:\\Windows\\Fonts\\arial.ttf'; $lines = explode("\n", $text); $lh = $size + 8; $start = $y + (int)(($h - count($lines)*$lh)/2) + $size;
    foreach ($lines as $i => $t) { $bb = imagettfbbox($size, 0, $font, $t); $tw = $bb[2]-$bb[0]; imagettftext($im,$size,0,$x+(int)(($w-$tw)/2),$start+$i*$lh,$black,$font,$t); }
}
function label($im, int $x, int $y, string $text, int $size = 24): void {
    $font = 'C:\\Windows\\Fonts\\arial.ttf'; $black = imagecolorallocate($im, 25, 25, 25); imagettftext($im,$size,0,$x,$y,$black,$font,$text);
}
function save($im, string $path): string { imagepng($im, $path); imagedestroy($im); return $path; }
function flowFigure(string $name, array $steps): string {
    [$im,$path,$w,$h] = canvas($name, 1400, 430); label($im, 50, 55, 'Current Business Process: Crime Incident Reporting and Recording', 28);
    $count = count($steps); $bw = 210; $gap = (int)((1300-$count*$bw)/($count-1)); foreach ($steps as $i=>$s) { $x=50+$i*($bw+$gap); box($im,$x,150,$bw,120,$s,18); if($i<$count-1) arrow($im,$x+$bw,210,$x+$bw+$gap-10,210); } return save($im,$path);
}
function architectureFigure(): string {
    [$im,$path] = canvas('architecture.png', 1400, 760); label($im,50,55,'Three-Tier System Architecture',28);
    box($im,100,115,1200,150,"PRESENTATION LAYER\nWeb browser interface: Login, Dashboard, Map, Crimes, Evidence, Reports",24);
    arrow($im,700,265,700,330); box($im,100,335,1200,170,"APPLICATION / BUSINESS LOGIC LAYER\nLaravel Controllers, Authentication, Role Authorization, Validation, Case Numbering, Analytics, Audit Logging",23);
    arrow($im,700,505,700,570); box($im,100,575,1200,130,"DATA LAYER\nMySQL Database and File Storage: Users, Crimes, Types, Barangays, Evidence, Audit Logs",24); return save($im,$path);
}
function ipoFigure(): string {
    [$im,$path] = canvas('conceptual_framework.png', 1400, 600); label($im,50,55,'Conceptual Framework: Input-Process-Output',28);
    box($im,55,160,360,280,"INPUT\nUser accounts and roles\nCrime reports and locations\nCrime/offense types\nBarangay boundaries\nEvidence files",22); arrow($im,420,300,505,300);
    box($im,510,160,380,280,"PROCESS\nAuthenticate users\nValidate and record crimes\nMap and locate incidents\nAttach evidence\nAnalyze and generate reports",22); arrow($im,895,300,980,300);
    box($im,985,160,360,280,"OUTPUT\nCrime case records\nInteractive crime map\nHotspot and trend analytics\nEvidence repository\nFiltered reports",22); return save($im,$path);
}
function useCaseFigure(): string {
    [$im,$path] = canvas('use_case.png', 1500, 900); label($im,50,55,'Use Case Diagram: Crime Mapping and Management System',28);
    $black=imagecolorallocate($im,35,35,35); imagesetthickness($im,3); imagerectangle($im,340,100,1320,840,$black); label($im,680,135,'Crime Mapping and Management System',22);
    foreach ([[60,210,'Police Officer'],[60,470,'Investigator'],[60,710,'Administrator'],[1360,450,'LGU User']] as [$x,$y,$t]) { imageellipse($im,$x+45,$y,30,30,$black); line($im,$x+45,$y+15,$x+45,$y+75); line($im,$x+15,$y+40,$x+75,$y+40); line($im,$x+45,$y+75,$x+20,$y+110); line($im,$x+45,$y+75,$x+70,$y+110); label($im,$x,$y+145,$t,18); }
    $cases=[[470,185,'Record Crime'],[770,185,'View Crime Map'],[1060,185,'Generate Reports'],[470,380,'Upload Evidence'],[770,380,'Update Case Status'],[1060,380,'View Analytics'],[470,590,'Manage Users'],[770,590,'Manage Reference Data'],[1060,590,'Review Audit Logs']];
    foreach($cases as [$x,$y,$t]) { imageellipse($im,$x+110,$y+35,220,70,$black); $bb=imagettfbbox(18,0,'C:\\Windows\\Fonts\\arial.ttf',$t); imagettftext($im,18,0,$x+110-(int)(($bb[2]-$bb[0])/2),$y+41,$black,'C:\\Windows\\Fonts\\arial.ttf',$t); }
    foreach ([[105,250,470,220],[105,250,470,415],[105,510,770,415],[105,510,770,220],[105,750,470,625],[105,750,770,625],[105,750,1060,625],[1405,490,770,220],[1405,490,1060,220],[1405,490,1060,415]] as $l) line($im,$l[0],$l[1],$l[2],$l[3],2); return save($im,$path);
}
function activityFigure(string $name, string $title, array $steps): string {
    [$im,$path] = canvas($name, 1400, 210 + count($steps)*110); label($im,50,55,$title,28); $x=490; imageellipse($im, $x+170,95,28,28,imagecolorallocate($im,35,35,35)); $y=125;
    foreach($steps as $i=>$s) { arrow($im,$x+170,$y,$x+170,$y+32); box($im,$x,$y+35,340,62,$s,19); $y += 97; } arrow($im,$x+170,$y,$x+170,$y+30); imagefilledellipse($im,$x+170,$y+48,30,30,imagecolorallocate($im,35,35,35)); return save($im,$path);
}
function wireframe(string $name, string $title, array $body): string {
    [$im,$path] = canvas($name, 1400, 850); $black=imagecolorallocate($im,35,35,35); imagesetthickness($im,4); imagerectangle($im,100,80,1300,780,$black); label($im,120,55,'LOW-FIDELITY WIREFRAME - '.$title,25);
    imagefilledrectangle($im,104,84,1296,145,imagecolorallocate($im,235,235,235)); line($im,104,145,1296,145); label($im,130,123,'CRIME MAPPING AND MANAGEMENT SYSTEM',18); label($im,1115,123,'[User] [Logout]',17);
    if ($title !== 'Login') { imagefilledrectangle($im,104,149,330,776,imagecolorallocate($im,245,245,245)); line($im,330,149,330,776); foreach(['Dashboard','Crime Records','Evidence','Map','Hotspots','Analytics','Reports','Users'] as $i=>$item) label($im,130,195+$i*60,'[ ] '.$item,17); }
    $left=$title==='Login'?340:365; $top=185; foreach($body as $entry) { [$x,$y,$w,$h,$txt]=$entry; box($im,$left+$x,$top+$y,$w,$h,$txt,17); } return save($im,$path);
}

$figures = [];
$figures['Figure 1. Current Business Process of Crime Incident Reporting and Recording'] = flowFigure('current_process.png',['Incident occurs','Citizen reports to police','Officer writes details manually','Supervisor reviews record','Office files paper report']);
$figures['Figure 2. Low-Fidelity Wireframe: Login Page'] = wireframe('wf_login.png','Login',[[170,80,430,60,'SYSTEM LOGO / IMAGE: X'],[170,190,430,55,'Username'],[170,260,430,55,'Password'],[170,340,430,55,'[ Login ]'],[170,430,430,40,'Forgot password?']]);
$figures['Figure 3. Low-Fidelity Wireframe: Dashboard with Navigation Bar'] = wireframe('wf_dashboard.png','Dashboard',[[0,0,900,55,'Dashboard'],[0,80,205,115,'Total Crimes\n[Count]'],[230,80,205,115,'Pending\n[Count]'],[460,80,205,115,'Resolved\n[Count]'],[690,80,205,115,'Closed\n[Count]'],[0,230,550,310,'MAP PLACEHOLDER: X'],[575,230,320,310,'Recent Crime Records\n[List]']]);
$figures['Figure 4. Low-Fidelity Wireframe: Crime Records and Delete Action'] = wireframe('wf_crimes.png','Crime Records',[[0,0,895,55,'Crime Records                    [ + Add Crime ]'],[0,85,895,50,'Search / Filter by type, barangay, date, status'],[0,160,895,320,'Case No. | Type | Location | Date | Status | Actions\n------------------------------------------------\nCRM-... | Theft | Barangay | Date | Pending | [View] [Edit] [Delete]\nCRM-... | Assault | Barangay | Date | Resolved | [View] [Edit] [Delete]'],[0,510,895,90,'Delete confirmation notification\nDelete this crime record? [Cancel] [Confirm Delete]']]);
$figures['Figure 5. Low-Fidelity Wireframe: Add/Edit Crime Record'] = wireframe('wf_crime_form.png','Add/Edit Crime Record',[[0,0,895,55,'Add Crime Record'],[0,85,430,55,'Crime Type'],[465,85,430,55,'Offense Type'],[0,165,430,55,'Date and Time'],[465,165,430,55,'Status'],[0,245,895,55,'Location / Barangay'],[0,325,895,175,'Description / Investigation Findings'],[0,530,430,55,'[ Cancel ]'],[465,530,430,55,'[ Save Record ]'],[0,615,895,60,'Notification: Record saved successfully.']]);
$figures['Figure 6. Low-Fidelity Wireframe: Reports'] = wireframe('wf_reports.png','Reports',[[0,0,895,55,'Crime Reports'],[0,85,210,55,'Crime Type Filter'],[230,85,210,55,'Barangay Filter'],[460,85,210,55,'Status Filter'],[690,85,205,55,'Date Range'],[0,170,895,55,'[ Generate Report ] [ Print / Export PDF ]'],[0,255,895,310,'REPORT PREVIEW\n[Table / Chart Placeholder]'],[0,600,895,60,'Notification: Report generated successfully.']]);
$figures['Figure 7. Low-Fidelity Wireframe: Notifications'] = wireframe('wf_notifications.png','Notifications',[[0,0,895,55,'Notifications'],[0,85,895,75,'Success: Crime record CRM-20260731-0001 was saved.'],[0,185,895,75,'Warning: Please complete required fields.'],[0,285,895,75,'Confirmation: Evidence upload completed.'],[0,385,895,75,'Error: You are not authorized to delete this record.']]);
$figures['Figure 8. Conceptual Framework of the Proposed System'] = ipoFigure();
$figures['Figure 9. Three-Tier System Architecture'] = architectureFigure();
$figures['Figure 10. Use Case Diagram of the Proposed System'] = useCaseFigure();
$figures['Figure 11. Activity Diagram for Recording a Crime Incident'] = activityFigure('activity_record.png','Activity Diagram: Recording a Crime Incident',['Officer signs in','Selects Add Crime Record','Enters validated incident details','System assigns case number','System saves record and audit log','System displays confirmation']);
$figures['Figure 12. Activity Diagram for Updating Case Status'] = activityFigure('activity_status.png','Activity Diagram: Updating a Case Status',['Investigator signs in','Opens a crime record','Reviews findings and evidence','Selects new status','System validates permission and saves','System records audit trail and notifies user']);

$doc = []; $rels=[]; $media=[]; $rid=1;
function para(string $text='', string $style='Normal', bool $bold=false): string { $r='<w:r>'.($bold?'<w:rPr><w:b/></w:rPr>':'').'<w:t xml:space="preserve">'.esc($text).'</w:t></w:r>'; return '<w:p><w:pPr><w:pStyle w:val="'.$style.'"/></w:pPr>'.$r.'</w:p>'; }
function bullets(array $items): string { $o=''; foreach($items as $item) $o.='<w:p><w:pPr><w:ind w:left="720" w:hanging="360"/></w:pPr><w:r><w:t>• </w:t></w:r><w:r><w:t>'.esc($item).'</w:t></w:r></w:p>'; return $o; }
function table(array $headers, array $rows): string { $s='<w:tbl><w:tblPr><w:tblBorders><w:top w:val="single" w:sz="8"/><w:left w:val="single" w:sz="8"/><w:bottom w:val="single" w:sz="8"/><w:right w:val="single" w:sz="8"/><w:insideH w:val="single" w:sz="4"/><w:insideV w:val="single" w:sz="4"/></w:tblBorders></w:tblPr>'; foreach(array_merge([$headers],$rows) as $ri=>$row){$s.='<w:tr>';foreach($row as $cell){$s.='<w:tc><w:tcPr><w:tcW w:w="'.(int)(9000/count($headers)).'" w:type="dxa"/></w:tcPr>'.para($cell,'Normal',$ri===0).'</w:tc>';}$s.='</w:tr>';} return $s.'</w:tbl>'; }
function imagePara(string $path, int $id, string $title): string { global $rels,$media; $name='image'.$id.'.png'; $media[$name]=$path; $rels[]='<Relationship Id="rId'.$id.'" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="media/'.$name.'"/>'; $size=getimagesize($path); $cx=(int)min(6200000, $size[0]*5000); $cy=(int)($size[1]*($cx/$size[0])); return '<w:p><w:pPr><w:jc w:val="center"/></w:pPr><w:r><w:drawing><wp:inline distT="0" distB="0" distL="0" distR="0" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing"><wp:extent cx="'.$cx.'" cy="'.$cy.'"/><wp:docPr id="'.$id.'" name="'.$name.'" descr="'.esc($title).'"/><a:graphic xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"><a:graphicData uri="http://schemas.openxmlformats.org/drawingml/2006/picture"><pic:pic xmlns:pic="http://schemas.openxmlformats.org/drawingml/2006/picture"><pic:nvPicPr><pic:cNvPr id="'.$id.'" name="'.$name.'"/><pic:cNvPicPr/></pic:nvPicPr><pic:blipFill><a:blip r:embed="rId'.$id.'" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"/><a:stretch><a:fillRect/></a:stretch></pic:blipFill><pic:spPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="'.$cx.'" cy="'.$cy.'"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></pic:spPr></pic:pic></a:graphicData></a:graphic></wp:inline></w:drawing></w:r></w:p>'; }
function pageBreak(): string { return '<w:p><w:r><w:br w:type="page"/></w:r></w:p>'; }

$doc[] = para('CHAPTER IV','Title'); $doc[] = para('METHODOLOGY, RESULTS, AND DISCUSSION','Subtitle'); $doc[] = para('Crime Mapping and Management System for Koronadal City','Subtitle');
$doc[] = para('4.1 Requirements Analysis','Heading1'); $doc[] = para('4.1.1 Current Technical Situation','Heading2');
$doc[] = para('The current handling of crime incidents in Koronadal City relies heavily on manual reporting, paper-based documentation, and separate records maintained by concerned offices. A citizen reports an incident to a police officer, who records the information and forwards it for review and filing. This arrangement makes it difficult to locate past cases quickly, track case progress, consolidate evidence, and identify geographic crime patterns. Information may be duplicated across forms, updates can be delayed, and decision makers do not have a single real-time view of crime incidents. The proposed Crime Mapping and Management System addresses these limitations by centralizing crime records, evidence, case-status monitoring, mapping, analytics, and reporting in one role-based web application.');
$doc[] = imagePara($figures['Figure 1. Current Business Process of Crime Incident Reporting and Recording'],$rid++,'Current business process'); $doc[] = para('Figure 1. Current Business Process of Crime Incident Reporting and Recording','Caption');
$doc[] = para('Figure 1 shows the existing process from the occurrence of an incident up to the filing of a paper report. The citizen provides incident details to the police officer, who manually writes the information before it is reviewed by a supervisor and stored in office files. Since the record is not immediately available in a centralized database, personnel must search physical documents when they need information about a case. The process also does not directly provide a map view, automated statistics, or an audit trail of updates.');
$doc[] = para('4.2 Requirements Documentation','Heading1'); $doc[] = para('The following low-fidelity wireframes serve as the blueprint of the proposed system. They use simple grayscale boxes, lines, and text placeholders to emphasize layout, navigation consistency, record actions, reports, and notifications before high-fidelity interface development.');
foreach(['Figure 2. Low-Fidelity Wireframe: Login Page','Figure 3. Low-Fidelity Wireframe: Dashboard with Navigation Bar','Figure 4. Low-Fidelity Wireframe: Crime Records and Delete Action','Figure 5. Low-Fidelity Wireframe: Add/Edit Crime Record','Figure 6. Low-Fidelity Wireframe: Reports','Figure 7. Low-Fidelity Wireframe: Notifications'] as $caption){$doc[]=imagePara($figures[$caption],$rid++,$caption);$doc[]=para($caption,'Caption');}
$doc[] = para('4.2.1 Functional Requirements','Heading2');
$functional = [['FR-01','The system shall allow authorized users to sign in, sign out, and reset passwords through OTP verification.'],['FR-02','The system shall provide role-based access for administrators, police officers, investigators, and LGU users.'],['FR-03','The system shall allow police officers to create crime records with type, offense type, date, location, barangay, description, and status.'],['FR-04','The system shall generate a unique case number for every new crime record.'],['FR-05','The system shall allow authorized personnel to view, search, filter, edit, and soft-delete crime records.'],['FR-06','The system shall display crime incidents on an interactive map and associate incidents with barangays.'],['FR-07','The system shall allow authorized users to upload, view, and manage evidence files attached to a crime record.'],['FR-08','The system shall allow investigators to record findings and update a case status.'],['FR-09','The system shall display dashboard counts, trends, hotspot data, and crime summaries by type, barangay, and status.'],['FR-10','The system shall generate filtered reports by crime type, barangay, status, and date range, with print/PDF output.'],['FR-11','The system shall allow administrators to manage user accounts, crime types, offense types, and barangay reference data.'],['FR-12','The system shall record audit logs for significant actions performed by users and show success, warning, confirmation, or error notifications.']];
$doc[] = table(['ID','Requirement'],$functional);
$doc[] = para('4.2.2 Non-Functional Requirements','Heading2');
$nonfunctional = [['Performance','Common dashboard, record-search, and report-filter requests should return within three seconds under normal use.'],['Reliability','Validated records, transactions, and audit logs shall reduce erroneous or incomplete data updates.'],['Availability','The web system shall be available to authorized offices during agreed service hours, subject to scheduled maintenance.'],['Security','Passwords shall be hashed; access shall be role-based; inputs shall be validated; sessions and file uploads shall be protected.'],['Usability','Screens shall keep navigation, buttons, labels, filters, and notifications consistent across major workflows.'],['Maintainability','The Laravel MVC structure, migrations, and separated models/controllers shall support controlled maintenance.'],['Scalability','Indexed columns and normalized tables shall support increasing crime records, evidence files, and users.'],['Compatibility','The system shall operate on current desktop browsers with a standard internet/intranet connection.'],['Portability','The application shall be deployable to a PHP/Laravel-compatible server with MySQL.'],['Data Integrity','Primary keys, foreign keys, validation rules, unique case numbers, and controlled reference tables shall preserve accurate data.']];
$doc[] = table(['Quality Attribute','Requirement'],$nonfunctional);
$doc[] = pageBreak(); $doc[] = para('4.3 Design of Software, System, Product, and/or Process','Heading1'); $doc[] = para('4.3.1 Conceptual Framework','Heading2');
$doc[] = para('The conceptual framework follows the Input-Process-Output model. Inputs include user accounts, incident information, crime and offense classifications, barangay data, and evidence files. The process authenticates users, validates and stores records, maps incident locations, manages evidence, monitors cases, and produces analytics and reports. The output is a centralized crime-management environment that provides current case information, spatial crime views, decision-support statistics, and accountable reporting.');
$doc[] = imagePara($figures['Figure 8. Conceptual Framework of the Proposed System'],$rid++,'Conceptual framework'); $doc[] = para('Figure 8. Conceptual Framework of the Proposed System','Caption');
$doc[] = para('4.3.2 System Architecture','Heading2'); $doc[] = para('The proposed system uses a three-tier architecture. In the presentation layer, authorized users access the web interface through their browsers to sign in, manage records, view maps, upload evidence, and generate reports. In the application or business-logic layer, the Laravel application handles authentication, role authorization, validation, case numbering, reporting, analytics, and audit logging. In the data layer, MySQL stores normalized operational data while configured file storage retains evidence documents. This separation improves maintainability, security, and scalability because user-interface, processing, and data responsibilities are managed independently.');
$doc[] = imagePara($figures['Figure 9. Three-Tier System Architecture'],$rid++,'Three tier architecture'); $doc[] = para('Figure 9. Three-Tier System Architecture','Caption');
$doc[] = para('4.3.3 Use Case Diagram','Heading2'); $doc[] = para('The use case diagram identifies the system actors and their major interactions. Police officers record incidents, attach evidence, and consult the map. Investigators review cases and update their status based on findings. Administrators manage users and reference data and review audit logs, while LGU users can view authorized map, analytics, and report information. These use cases represent the core functional requirements of the system.');
$doc[] = imagePara($figures['Figure 10. Use Case Diagram of the Proposed System'],$rid++,'Use case diagram'); $doc[] = para('Figure 10. Use Case Diagram of the Proposed System','Caption');
$doc[] = para('4.3.4 Activity Diagrams','Heading2'); $doc[] = para('The first activity diagram describes the process for recording a crime incident. The activity begins when a police officer signs in, enters validated details, and submits the record. The system assigns a case number, saves the record, creates an audit entry, and confirms the result. The second activity diagram covers case-status updates, where an investigator reviews the relevant case and evidence before selecting an authorized status change that is validated and logged by the system.');
foreach(['Figure 11. Activity Diagram for Recording a Crime Incident','Figure 12. Activity Diagram for Updating Case Status'] as $caption){$doc[]=imagePara($figures[$caption],$rid++,$caption);$doc[]=para($caption,'Caption');}
$doc[] = pageBreak(); $doc[] = para('4.4 Database Normalization','Heading1'); $doc[] = para('Before normalization, the proposed database stores operational information about users, crime records, classifications, barangays, evidence files, and audit activities. Normalization is applied to eliminate repeating groups, reduce data duplication, and maintain dependable relationships among records.');
$doc[] = para('4.4.1 Unnormalized Form (UNF)','Heading2'); $doc[] = para('A single unnormalized crime-report record may contain multiple evidence names and file paths in repeating columns, as well as repeating crime-type, offense-type, barangay, and officer details. This structure is difficult to extend because every new evidence item would require another column.');
$doc[] = table(['Case No.','Crime Type','Evidence 1','Evidence 2','Officer Name','Barangay'],[['CRM-20260731-0001','Theft','Photo A','Statement A','Juan Dela Cruz','General Paulino Santos']]);
$doc[] = para('4.4.2 First Normal Form (1NF)','Heading2'); $doc[] = para('In 1NF, each field contains only one value. Repeating evidence groups are removed by storing each evidence item in a separate row. Although the data is atomic, case, type, barangay, and officer details may still repeat for every evidence row.');
$doc[] = table(['Case No.','Crime Type','Evidence File','Officer Name','Barangay'],[['CRM-20260731-0001','Theft','Photo A','Juan Dela Cruz','General Paulino Santos'],['CRM-20260731-0001','Theft','Statement A','Juan Dela Cruz','General Paulino Santos']]);
$doc[] = para('4.4.3 Second Normal Form (2NF)','Heading2'); $doc[] = para('In 2NF, attributes that depend only on part of a composite relationship are separated. Crime details are kept in the Crimes table, while evidence details are moved to an Evidence table linked by crime_id. Reference data such as crime type and barangay are also separated so their names are not repeated in every crime record.');
$doc[] = table(['Table','Primary Key','Key Attributes'],[['Crimes','crime_id','case_number, crime_type_id, barangay_id, reported_by, status'],['Evidence','evidence_id','crime_id, file_name, file_path, uploaded_by'],['CrimeTypes','crime_type_id','name, description, is_active'],['Barangays','barangay_id','name, boundaries']]);
$doc[] = para('4.4.4 Third Normal Form (3NF)','Heading2'); $doc[] = para('In 3NF, non-key attributes depend only on their table primary key. Offense types are stored independently and referenced by crimes; users are stored separately from the crimes they report or the evidence they upload; and audit data is placed in its own table. The resulting design prevents transitive dependencies and makes names, classifications, and account details easier to update without changing historical crime records.');
$doc[] = table(['Table','Primary Key','Foreign Keys / Main Attributes'],[['users','id','name, email, password, role, is_active'],['crime_types','id','name, description, is_active'],['offense_types','id','crime_type_id, name, description, is_active'],['barangays','id','name, boundary data'],['crimes','id','crime_type_id, offense_type_id, barangay_id, reported_by, case_number, date, location, status'],['evidence','id','crime_id, uploaded_by, file_name, file_path, file_type, description'],['audit_logs','id','user_id, action, auditable_type, auditable_id, old_values, new_values']]);
$doc[] = para('The final 3NF design supports consistent reporting and protects data integrity through primary keys, foreign keys, controlled reference tables, unique case numbers, and audit logging.');

$body = implode('', $doc) . '<w:sectPr><w:pgSz w:w="12240" w:h="15840"/><w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440"/></w:sectPr>';
$documentXml = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing" xmlns:pic="http://schemas.openxmlformats.org/drawingml/2006/picture"><w:body>'.$body.'</w:body></w:document>';
$styles = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:docDefaults><w:rPrDefault><w:rPr><w:rFonts w:ascii="Arial" w:hAnsi="Arial"/><w:sz w:val="22"/></w:rPr></w:rPrDefault></w:docDefaults><w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/><w:pPr><w:spacing w:after="120" w:line="276" w:lineRule="auto"/></w:pPr></w:style><w:style w:type="paragraph" w:styleId="Title"><w:name w:val="Title"/><w:rPr><w:b/><w:sz w:val="32"/></w:rPr><w:pPr><w:jc w:val="center"/><w:spacing w:after="180"/></w:pPr></w:style><w:style w:type="paragraph" w:styleId="Subtitle"><w:name w:val="Subtitle"/><w:rPr><w:b/><w:sz w:val="24"/></w:rPr><w:pPr><w:jc w:val="center"/><w:spacing w:after="120"/></w:pPr></w:style><w:style w:type="paragraph" w:styleId="Heading1"><w:name w:val="heading 1"/><w:rPr><w:b/><w:sz w:val="28"/></w:rPr><w:pPr><w:spacing w:before="300" w:after="160"/></w:pPr></w:style><w:style w:type="paragraph" w:styleId="Heading2"><w:name w:val="heading 2"/><w:rPr><w:b/><w:sz w:val="24"/></w:rPr><w:pPr><w:spacing w:before="220" w:after="100"/></w:pPr></w:style><w:style w:type="paragraph" w:styleId="Caption"><w:name w:val="Caption"/><w:rPr><w:i/><w:sz w:val="20"/></w:rPr><w:pPr><w:jc w:val="center"/><w:spacing w:after="160"/></w:pPr></w:style></w:styles>';
$target=__DIR__.DIRECTORY_SEPARATOR.'IT_Capstone_Project_2_Chapter_IV_Crime_Management_System.docx'; $zip=new ZipArchive(); if($zip->open($target,ZipArchive::CREATE|ZipArchive::OVERWRITE)!==true) die('Cannot create document.');
$zip->addFromString('[Content_Types].xml','<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Default Extension="png" ContentType="image/png"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/></Types>');
$zip->addFromString('_rels/.rels','<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>');
$zip->addFromString('word/document.xml',$documentXml); $zip->addFromString('word/styles.xml',$styles); $zip->addFromString('word/_rels/document.xml.rels','<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rIdStyles" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>'.implode('',$rels).'</Relationships>'); foreach($media as $name=>$path)$zip->addFile($path,'word/media/'.$name); $zip->close();
echo $target, PHP_EOL;
